version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./models:/app/models
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped 